# Generated by Django 5.2.4 on 2025-07-23 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_bookcover_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcover',
            name='user',
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='author_book',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='dedication',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='template',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
