# Generated by Django 5.2.4 on 2025-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_bookcover_user_alter_bookcover_author_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='author_book',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='template',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
