# Generated by Django 5.2.4 on 2025-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_bookcover_author_book_alter_bookcover_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='author_book',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='cover_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='dedication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
