# Generated by Django 5.2.4 on 2025-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_bookcover_author_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
